---
title: "看板|人民币贷款"
author: "胡华平"
format: dashboard
---

## Column {height=90% .tabset}

```{r}
#| title: "住户短期VS中长期贷款趋势（月度，万亿元）"
#| echo: false
#| warning: false
#| message: false
library(here)
script_path <- here("trend", "code", "viz-credit-funds-source-use.R")
source(script_path)
p_short_long_plotly
```

```{r}
#| title: "住户短期贷款构成变化趋势（月度，亿元）"
#| echo: false
#| warning: false
#| message: false
p_short_plotly
```

```{r}
#| title: "住户中长期贷款构成变化趋势（月度，亿元）"
#| echo: false
#| warning: false
#| message: false
p_long_plotly
```


## Row {height=10%}

::: {.card}

> 数据来源：中国人民银行官方网站 (www.pbc.gov.cn) 。月度发布，金融机构人民币信贷收支表（Sources & Uses of Credit Funds of Financial Institutions (RMB)）。 查找路径：统计数据->2025年统计数据 -> 金融机构信贷收支统计 <http://www.pbc.gov.cn/diaochatongjisi/116219/116319/5570903/5570888/index.html>。
:::

<!-- ### 简要结论

数据还显示，2025年4月末人民币贷款余额265.7万亿元，同比增长7.2%，较上月末下降了0.2个百分点。从增量看，前四个月人民币贷款增加10.06万亿元，同比少增0.13万亿元。

分部门看，住户贷款增加5184亿元，其中，短期贷款减少2416亿元，中长期贷款增加7601亿元；企（事）业单位贷款增加9.27万亿元，其中，短期贷款增加3.03万亿元，中长期贷款增加5.83万亿元，票据融资增加2899亿元；非银行业金融机构贷款增加768亿元。 -->

<!-- 从居民部门看，前四个月短期、中长期贷款分别同比少增2466亿元、483亿元。 中国银行研究院研究员梁斯认为，这或与4月份房地产市场运行情况有关。2025年4月，30个大中城市商品房成交面积、成交套数为686.02万平方米、6.12万套，同比下降12.06%和11.73%。在经历“小阳春”后，4月份房地产市场热度有所下降，全国房产经纪行业景气度指数为 44.6，与 3月相比下降10 点。

从企业部门看，企（事）业单位短期、中长期贷款分别多增4700亿元、少增7800亿元。梁斯表示，企业短期贷款多增、中长期贷款少增或与4月份外部环境发生急剧变化，导致企业未来预期不确定性增大有关。 -->












